#!/bin/sh

#Author: Vatsaev Aslan (@avatsaev)
#Repository: https://github.com/avatsaev/mackeeper_blocker

sudo echo "\n127.0.0.1 mackeeper.com mackeeperapp.mackeeper.com mackeeperapp2.mackeeper.com mackeeperapp3.mackeeper.com\n" >> /etc/hosts
